fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: website.mail237@gmail.com #email de l'expediteur
        sender_name: Tournois
    registration:
        confirmation:
            enabled: false
            from_email:
                address:        website.mail237@gmail.com
                sender_name:    Tournois
            template:   '@FOSUser/Registration/email.txt.twig'
    resetting:
        email:
            from_email:
                address:        website.mail237@gmail.com
                sender_name:    Tournois
            template:   '@FOSUser/Resetting/email.txt.twig'